# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('pid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=30)),
                ('lon', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('checkinNum', models.IntegerField(default=0)),
                ('checkinUserNum', models.IntegerField(default=0)),
                ('todoNum', models.IntegerField(default=0)),
                ('likeNum', models.IntegerField(default=0)),
            ],
        ),
    ]
