# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=30)),
                ('lon', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('checkinNum', models.IntegerField(default=0)),
                ('checkinUserNum', models.IntegerField(default=0)),
                ('todoNum', models.IntegerField(default=0)),
                ('likeNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisManage.POI'),
        ),
    ]
