# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poisManage', '0001_initial'),
        ('poisRecommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisManage.POI')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisManage.POI')),
            ],
        ),
        migrations.RenameField(
            model_name='data_user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisRecommend.data_user'),
        ),
        migrations.AddField(
            model_name='like',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisRecommend.data_user'),
        ),
    ]
