# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisRecommend', '0002_auto_20160526_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_user',
            name='city',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='data_user',
            name='province',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
